baseURL = 'https://justintheyang.github.io/'
languageCode = 'en-us'
title = 'Justin Yang'
theme = 'barks'

[params.head]
    author = "Justin Yang"
    description = "Hi, I'm Justin, and this is my website!"
    keywords = ["some", "keywords", "to", "describe", "this"]

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:justin.yang@stanford.edu"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/justintheyang"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=otxsJugAAAAJ"
        weight = 3
