baseURL = 'https://justintheyang.github.io/'
languageCode = 'en-us'
title = 'Justin Yang'
theme = ["hugo-embed-pdf-shortcode", "barks"]
enableInlineShortcodes = true

[params.head]
    author = "Justin Yang"
#    description = "Hi, I'm Justin! I'm a data scientist at Signifyd, where I build machine learning models to detect fraud."
    keywords = [
      "cognitive science", "psychology", "computation", "causality", "representation", 
      "personal website", "uc san diego", "stanford", "data scientist"]
    favicon = "favicon_loss.png"

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:justin.yang@stanford.edu"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/justintheyang"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=otxsJugAAAAJ"
        weight = 3

[params.colors]
    theme_color = "#333333"
    background_color = "#fcfbf9"
    text_color = "#333333"
    link_color = "#60c17d"

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 1

  # [[menu.main]]
  #   identifier = "projects"
  #   name = "Projects"
  #   url = "/projects/"
  #   weight = 2

  [[menu.main]]
    identifier = "demos"
    name = "Demos"
    url = "/demos/"
    weight = 3

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/Resume/"
    weight = 4

